sudo: true

before_install:
        - wget http://adamryman.com/files/splunk.deb
        - sudo dpkg -i splunk.deb
        - sudo /opt/splunk/bin/start --accept-license
language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6
  - 0.8

