sudo: true

before_install:
        - wget http://adamryman.com/files/splunk_64.tgz
        - tar xzf splunk_64.tgz
        - uname -a
        - echo $SPLUNK_HOME
        - ls
        - cd splunk
        - ls
        - cd bin
        - ls
        - echo $SPLUNK_HOME
        - sudo ./splunk validate audit
        - sudo ./splunk start --accept-license
        - cd ..
        - cd ..

language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.8

