sudo: true

before_install:
        - wget http://adamryman.com/files/splunk_64.tgz
        - tar xzf splunk_64.tgz
        - rm splunk_64.tgz
        - sudo dd if=/dev/zero of=./splunkfs.img bs=1M count=100
        - sudo mkfs.ext4 splunkfs.img
        - sudo mount splunkfs.img ./splunk/var
        - uname -a
        - echo $SPLUNK_HOME
        - ls
        - cd splunk
        - ls
        - cd bin
        - ls
        - echo $SPLUNK_HOME
        - sudo ./splunk start --accept-license
        - cd ..
        - cd ..

language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.8

